apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: obkr8x65f-python
  janus-idp.io/tekton: obkr8x65f-python
  backstage.io/kubernetes-id: obkr8x65f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: obkr8x65f-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
